default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: reverser_development

test:
  <<: *default
  database: reverser_test

production:
  <<: *default
  database: reverser_production
  username: reverser
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>